module.exports = {
	plugins: ['prettier-plugin-tailwindcss'],
	embeddedLanguageFormatting: 'auto',
	htmlWhitespaceSensitivity: 'css',
	vueIndentScriptAndStyle: false,
	quoteProps: 'as-needed',
	proseWrap: 'preserve',
	jsxSingleQuote: false,
	trailingComma: 'es5',
	requirePragma: false,
	bracketSpacing: true,
	arrowParens: 'avoid',
	insertPragma: false,
	singleQuote: true,
	endOfLine: 'auto',
	printWidth: 120,
	useTabs: true,
	tabWidth: 2,
	semi: false,
}
