module.exports = {
	vueIndentScriptAndStyle: false,
	useTabs: true,
	trailingComma: 'es5',
	tabWidth: 2,
	singleQuote: true,
	semi: false,
	requirePragma: false,
	quoteProps: 'as-needed',
	proseWrap: 'preserve',
	printWidth: 120,
	plugins: ['prettier-plugin-tailwindcss'],
	jsxSingleQuote: false,
	insertPragma: false,
	htmlWhitespaceSensitivity: 'css',
	endOfLine: 'auto',
	embeddedLanguageFormatting: 'auto',
	bracketSpacing: true,
	arrowParens: 'avoid',
}
